/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.juegos;

import java.awt.Image;
import java.awt.Toolkit;
import ventanas.buena;
import ventanas.inicio;
import ventanas.mala;

/**
 *
 * @author Erika Sanchez
 */
public class jugar01 extends javax.swing.JFrame {

    /**
     * Creates new form jugar1
     */
    public jugar01() {
        initComponents();
    this.setLocationRelativeTo(null);
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img_inicio/logo.png"));
        return retValue;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jba = new javax.swing.JButton();
        jbb = new javax.swing.JButton();
        jbc = new javax.swing.JButton();
        jbd = new javax.swing.JButton();
        jbe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_info/volver11.png"))); // NOI18N
        volver.setBorder(null);
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setFocusPainted(false);
        volver.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img_info/volver12.png"))); // NOI18N
        volver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img_info/volver10.png"))); // NOI18N
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 150, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_preguntas/1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_preguntas/1a.png"))); // NOI18N
        jba.setBorder(null);
        jba.setBorderPainted(false);
        jba.setContentAreaFilled(false);
        jba.setFocusPainted(false);
        jba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaActionPerformed(evt);
            }
        });
        getContentPane().add(jba, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jbb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_preguntas/1b.png"))); // NOI18N
        jbb.setBorder(null);
        jbb.setBorderPainted(false);
        jbb.setContentAreaFilled(false);
        jbb.setFocusPainted(false);
        jbb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbbMouseClicked(evt);
            }
        });
        jbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbActionPerformed(evt);
            }
        });
        getContentPane().add(jbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jbc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_preguntas/1c.png"))); // NOI18N
        jbc.setBorder(null);
        jbc.setBorderPainted(false);
        jbc.setContentAreaFilled(false);
        jbc.setFocusPainted(false);
        jbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcActionPerformed(evt);
            }
        });
        getContentPane().add(jbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jbd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_preguntas/1d.png"))); // NOI18N
        jbd.setBorder(null);
        jbd.setBorderPainted(false);
        jbd.setContentAreaFilled(false);
        jbd.setFocusPainted(false);
        jbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdActionPerformed(evt);
            }
        });
        getContentPane().add(jbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jbe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_preguntas/1e.png"))); // NOI18N
        jbe.setBorder(null);
        jbe.setBorderPainted(false);
        jbe.setContentAreaFilled(false);
        jbe.setFocusPainted(false);
        jbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeActionPerformed(evt);
            }
        });
        getContentPane().add(jbe, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_jugar/fjugar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        //Vuelve a inicio
        inicio obj =new inicio();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void jbbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbbMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbbMouseClicked

    private void jbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbActionPerformed
        //Va a pantalla buena
        buena obj =new buena();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbbActionPerformed

    private void jbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaActionPerformed
        //Va a pantalla mala
        mala obj =new mala();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbaActionPerformed

    private void jbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcActionPerformed
        //Va a pantalla mala
        mala obj =new mala();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbcActionPerformed

    private void jbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdActionPerformed
        //Va a pantalla mala
        mala obj =new mala();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbdActionPerformed

    private void jbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeActionPerformed
        //Va a pantalla mala
        mala obj =new mala();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jugar01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jugar01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jugar01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jugar01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jugar01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jba;
    private javax.swing.JButton jbb;
    private javax.swing.JButton jbc;
    private javax.swing.JButton jbd;
    private javax.swing.JButton jbe;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
