/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.awt.Image;
import java.awt.Toolkit;
import ventanas.juegos.jugar0;
import ventanas.juegos.jugar01;
import ventanas.juegos.jugar02;
import ventanas.juegos.jugar03;
import ventanas.juegos.jugar04;
import ventanas.juegos.jugar05;
import ventanas.juegos.jugar06;
import ventanas.juegos.jugar07;
/**
 *
 * @author Erika Sanchez
 */
public class inicio extends javax.swing.JFrame {
    public static int v=3;
    public static int pt=0;

    static void txtvida(int i) {
        
    }

    static void txtpuntos(int i) {
        
    }


    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img_inicio/logo.png"));
        return retValue;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugar = new javax.swing.JButton();
        info = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        inicio = new javax.swing.JLabel();
        txtvida = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/jugar2.png"))); // NOI18N
        jugar.setBorder(null);
        jugar.setBorderPainted(false);
        jugar.setContentAreaFilled(false);
        jugar.setFocusPainted(false);
        jugar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/jugar3.png"))); // NOI18N
        jugar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/jugar.png"))); // NOI18N
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });
        getContentPane().add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/bt_info2.png"))); // NOI18N
        info.setBorder(null);
        info.setBorderPainted(false);
        info.setContentAreaFilled(false);
        info.setFocusPainted(false);
        info.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/bt_info3.png"))); // NOI18N
        info.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/bt_info.png"))); // NOI18N
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        getContentPane().add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/salir2.png"))); // NOI18N
        salir.setBorder(null);
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setFocusPainted(false);
        salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/salir3.png"))); // NOI18N
        salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/salir.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, -1, -1));

        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_inicio/inicio.png"))); // NOI18N
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(txtvida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 710, 100, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // Para salir
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // Conecta con la pàgina de info
        new info().setVisible(true);
        dispose();
    }//GEN-LAST:event_infoActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        int j;
        j = (int) Math.floor(Math.random()*8);
        if(j<1){
            jugar0 obj = new jugar0();
            obj.setVisible(true);
            dispose();
        }else{
            if((j<2)&&(j>0)){
                            jugar01 obj = new jugar01();
                            obj.setVisible(true);
                            dispose();
            }else{
                if((j<3)&&(j>1)){
                            jugar02 obj = new jugar02();
                            obj.setVisible(true);
                            dispose();
                }else{
                    if((j<4)&&(j>2)){
                            jugar03 obj = new jugar03();
                            obj.setVisible(true);
                            dispose();
                    }else{
                        if((j<5)&&(j>3)){
                            jugar04 obj = new jugar04();
                            obj.setVisible(true);
                            dispose();
                        }else{
                            if((j<6)&&(j>4)){
                            jugar05 obj = new jugar05();
                            obj.setVisible(true);
                            dispose();
                            }else{
                    if((j<7)&&(j>5)){
                            jugar06 obj = new jugar06();
                            obj.setVisible(true);
                            dispose();
                    }else{
                        if((j<8)&&(j>6)){
                            jugar07 obj = new jugar07();
                            obj.setVisible(true);
                            dispose();
                    }
                    
                    }
                    
                    }
                }
            }
        }
      }   
        }        
    }//GEN-LAST:event_jugarActionPerformed

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton info;
    private javax.swing.JLabel inicio;
    public static javax.swing.JTextField jTextField1;
    private javax.swing.JButton jugar;
    private javax.swing.JButton salir;
    public static javax.swing.JTextField txtvida;
    // End of variables declaration//GEN-END:variables

    

   
}
