/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import static ventanas.inicio.v;
import ventanas.juegos.jugar0;
import ventanas.juegos.jugar01;
import ventanas.juegos.jugar02;
import ventanas.juegos.jugar03;
import ventanas.juegos.jugar04;
import ventanas.juegos.jugar05;
import ventanas.juegos.jugar06;
import ventanas.juegos.jugar07;

/**
 *
 * @author Erika Sanchez
 */
public class mala extends javax.swing.JFrame {
    public static int j;
    /**
     * Creates new form mala
     */
    public mala() {
        initComponents();
        this.setLocationRelativeTo(null);
        j = (int) Math.floor(Math.random()*8);
        ventanas.inicio.txtvida(v--);
       
       
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img_inicio/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_otros/seguir2.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img_otros/seguir3.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img_otros/seguir.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_otros/pmala.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if((v<4)&&(v!=0)){
        if(j<1){
            new jugar0().setVisible(true);
            dispose();
        }else{
            if((j<2)&&(j>0)){
                            new jugar01().setVisible(true);
                            dispose();
            }else{
                if((j<3)&&(j>1)){
                            new jugar02().setVisible(true);
                            dispose();
                }else{
                    if((j<4)&&(j>2)){
                            new jugar03().setVisible(true);
                            dispose();
                    }else{
                        if((j<5)&&(j>3)){
                            new jugar04().setVisible(true);
                            dispose();
                        }else{
                            if((j<6)&&(j>4)){
                            new jugar05().setVisible(true);
                            dispose();
                            }else{
                    if((j<7)&&(j>5)){
                            new jugar06().setVisible(true);
                            dispose();
                    }else{
                        if((j<8)&&(j>6)){
                            new jugar07().setVisible(true);
                            dispose();
                    }
                    
                    }
                    
                    }
                }
            }
        }
      }   
        }
        }else{
            v=3;
            new inicio().setVisible(true);
            dispose();
        }
       
        
        
   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mala().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
}
