package IniciarSesion;

import Administrador.WinAdministrador;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JOptionPane;

public class Iniciarsesion extends javax.swing.JFrame {
    
    File  f = null; 
    FileReader fr = null; 
    BufferedReader br = null; 
    String user, pass;
    
    public Iniciarsesion() {
        initComponents();
        //Iniciamos la ventana siempre centrada
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusuario = new javax.swing.JTextField();
        txtcontra = new javax.swing.JPasswordField();
        btnentrar = new javax.swing.JButton();
        jcbtipouser = new javax.swing.JComboBox<>();
        jlbtipouser = new javax.swing.JLabel();
        btncerrar = new javax.swing.JButton();
        btnminimizar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtusuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtusuario.setBorder(null);
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 240, 20));

        txtcontra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcontra.setBorder(null);
        getContentPane().add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 250, -1));

        btnentrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnentrar.setText("Ingresar");
        btnentrar.setBorderPainted(false);
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, 120, 40));

        jcbtipouser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbtipouser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Bibliotecario", "Lector" }));
        jcbtipouser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jcbtipouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 160, 30));

        jlbtipouser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbtipouser.setText("Tipo de usuario");
        getContentPane().add(jlbtipouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 514, 140, 20));

        btncerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncerrar.setForeground(new java.awt.Color(242, 98, 28));
        btncerrar.setText("X");
        btncerrar.setBorder(null);
        btncerrar.setContentAreaFilled(false);
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 20, -1));

        btnminimizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnminimizar.setForeground(new java.awt.Color(242, 98, 28));
        btnminimizar.setText("_");
        btnminimizar.setBorder(null);
        btnminimizar.setContentAreaFilled(false);
        btnminimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal.jpg"))); // NOI18N
        fondo.setToolTipText("");
        fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fondoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fondoMouseReleased(evt);
            }
        });
        fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fondoMouseDragged(evt);
            }
        });
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx,xy;
    private void btnminimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnminimizarActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btncerrarActionPerformed

    private void fondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMousePressed
        setOpacity((float)0.8);
                xx=evt.getX();
                xy=evt.getY();
    }//GEN-LAST:event_fondoMousePressed

    private void fondoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_fondoMouseReleased

    private void fondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_fondoMouseDragged

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
        String tipo = jcbtipouser.getSelectedItem().toString();
        String usuario = txtusuario.getText();
        String contra = txtcontra.getText();
        boolean usuarioValido = autenticarUsuario(usuario, contra);
            if(usuarioValido){
                new WinAdministrador().setVisible(true);
                dispose();
            }else
                JOptionPane.showMessageDialog(null, "Usuario NO válido");
    }//GEN-LAST:event_btnentrarActionPerformed

    public boolean autenticarUsuario(String usuario, String contra){
        try {
            f = new File("usuarios.txt");
            fr = new FileReader(f);
            br = new BufferedReader(fr);
            String linea;
            while((linea = br.readLine()) != null){
                String datos[] = linea.split(",");
                user = datos[0];  
                pass = datos[1];   
                if(user.equals(usuario) && pass.equals(contra))
                    return true;
            }
            fr.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error = " + e.toString());
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciarsesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciarsesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciarsesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciarsesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciarsesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btnentrar;
    private javax.swing.JButton btnminimizar;
    private javax.swing.JLabel fondo;
    private javax.swing.JComboBox<String> jcbtipouser;
    private javax.swing.JLabel jlbtipouser;
    private javax.swing.JPasswordField txtcontra;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
